version: '3.8'

services:
  Dell_iDRAC_fan_controller:
    image: tigerblue77/dell_idrac_fan_controller:latest
    container_name: Dell_iDRAC_fan_controller
    restart: unless-stopped
    environment:
      - IDRAC_HOST=xxx.xxx.xxx.xxx
      - IDRAC_USERNAME=fan
      - IDRAC_PASSWORD=fan
      - FAN_SPEED=0x08
      - CPU_TEMPERATURE_THRESHOLD=50
      - CHECK_INTERVAL=30
      - DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE=false
