#!/bin/bash
sudo IDRAC_HOST=192.168.2.21 FAN_SPEED=7 CPU_TEMPERATURE_THRESHOLD=65 CPU_TEMPERATURE_SETPOINT=60 CHECK_INTERVAL=1 DISABLE_THIRD_PARTY_PCIE_CARD_DELL_DEFAULT_COOLING_RESPONSE=true ./Dell_iDRAC_PID_fan_controller.sh
